### ISSUE TITLE
How to deal with different dataset like cornell to implement this code

### ISSUE THREAD

**Issue by asmaadaoud** [fahim-sikder/Node-Classification-GCN#1]
when i run this code with cornell dataset (the files of this data are txt files) give me an error.  does this require converting file to cornell.content
please, kindly reply

**Comment by fahim-sikder** [comment]
Hi, sorry for the late feedback, I have updated the code, the error was given for old version of numpy, I fixed it, the current code should run with latest version of torch and numpy. Hope it helps,
